clc;close; clear all;
vmax = 8;
n = 3;
fm = 70;
fs = 2000;
t = 0:1/fs:1/fm;
x = vmax * sin(2*pi*fm*t);
vmin = -vmax;
L = 2^n;
del = (vmax - vmin) / L;
part = vmin + del : del : vmax - del;
code = vmin + del/2 : del : vmax - del/2;
[ind, q] = quantiz(x, part, code);
ind = max(ind - 1, 0);
code_bin = de2bi(ind, n, 'left-msb');
coded = reshape(code_bin', 1, []);
t2 = linspace(0, max(t), length(coded));
subplot(221); plot(t, x); title('Analog Signal'); xlabel('Time'); ylabel('Amplitude');grid on;
subplot(222); stem(t, x); title('Sampled Signal'); xlabel('Samples'); ylabel('Amplitude');grid on;
subplot(223); stairs(t, q); hold on; plot(t, x, '--r'); title('Quantized Signal'); xlabel('Time'); ylabel('Amplitude');grid on;
subplot(224); stairs(t2, coded); title('Encoded Signal (PCM Bitstream)'); xlabel('Samples'); ylabel('Bit Value');grid on;ylim([-0.5 1.5]);
